/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FollowingService } from "../following.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FollowingCreateInput } from "./FollowingCreateInput";
import { Following } from "./Following";
import { FollowingFindManyArgs } from "./FollowingFindManyArgs";
import { FollowingWhereUniqueInput } from "./FollowingWhereUniqueInput";
import { FollowingUpdateInput } from "./FollowingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FollowingControllerBase {
  constructor(
    protected readonly service: FollowingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Following })
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFollowing(
    @common.Body() data: FollowingCreateInput
  ): Promise<Following> {
    return await this.service.createFollowing({
      data: {
        ...data,

        trader: data.trader
          ? {
              connect: data.trader,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Following] })
  @ApiNestedQuery(FollowingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async followings(@common.Req() request: Request): Promise<Following[]> {
    const args = plainToClass(FollowingFindManyArgs, request.query);
    return this.service.followings({
      ...args,
      select: {
        createdAt: true,
        id: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Following })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async following(
    @common.Param() params: FollowingWhereUniqueInput
  ): Promise<Following | null> {
    const result = await this.service.following({
      where: params,
      select: {
        createdAt: true,
        id: true,

        trader: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Following })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFollowing(
    @common.Param() params: FollowingWhereUniqueInput,
    @common.Body() data: FollowingUpdateInput
  ): Promise<Following | null> {
    try {
      return await this.service.updateFollowing({
        where: params,
        data: {
          ...data,

          trader: data.trader
            ? {
                connect: data.trader,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Following })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Following",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFollowing(
    @common.Param() params: FollowingWhereUniqueInput
  ): Promise<Following | null> {
    try {
      return await this.service.deleteFollowing({
        where: params,
        select: {
          createdAt: true,
          id: true,

          trader: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
