/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FollowingListRelationFilter } from "../../following/base/FollowingListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PositionListRelationFilter } from "../../position/base/PositionListRelationFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

@InputType()
class TraderWhereInput {
  @ApiProperty({
    required: false,
    type: () => FollowingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FollowingListRelationFilter)
  @IsOptional()
  @Field(() => FollowingListRelationFilter, {
    nullable: true,
  })
  followings?: FollowingListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PositionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PositionListRelationFilter)
  @IsOptional()
  @Field(() => PositionListRelationFilter, {
    nullable: true,
  })
  positions?: PositionListRelationFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  score?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  traderId?: StringNullableFilter;
}

export { TraderWhereInput as TraderWhereInput };
